image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.7-builder"

cache:
  paths:
    - vendor/ruby

stages:
  - build
  - upload

build:
  stage: build
  image: node
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - build

deploy:
  stage: upload
  only:
    - master
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - echo 'Deploying to Antagonist'
    - rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./build/ $SSH_USER@$SERVER_IP:~/roqua_docs2/html
  artifacts:
    paths:
    - public
