image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.7-builder"

cache:
  paths:
    - vendor/ruby

stages:
  - test
  - post-test

test:
  stage: test
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
  - ruby -v
  - gem install bundler
  - bundle install --path vendor
  - bundle exec nanoc compile
  #- bundle exec rake test
  - bundle exec nanoc check ilinks
  - mv output public
  - echo 'Deploying to Antagonist'
  - rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./public/ roquadocs@141.138.168.34:~/public_html
  artifacts:
    paths:
    - public

deploy:
  stage: post-test
  only:
    - master
  dependencies:
    - test
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - echo 'Deploying to Antagonist'
    - rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./public/ roquadocs@141.138.168.34:~/public_html
  artifacts:
    paths:
    - public