image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.7-builder"

cache:
  paths:
    - vendor/ruby

stages:
  - test
  - post-test

test:
  stage: test
  script:
  - ruby -v
  - gem install bundler
  - bundle install --path vendor
  - bundle exec nanoc compile
  #- bundle exec rake test
  - bundle exec nanoc check ilinks
  - mv output public
  artifacts:
    paths:
    - public

pages:
  stage: post-test
  only:
    - master
  dependencies:
    - test
  script:
    - echo 'Deploying to GitLab Pages'
  artifacts:
    paths:
    - public
