// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightLinksValidator from "starlight-links-validator";

export default defineConfig({
  site: "https://docs.roqua.net",

  // The manual root used to be /docs/index/, an artifact of the `01-index.md`
  // numeric prefix. It was the navbar's "User Manual" target, so keep it working.
  redirects: {
    "/docs/index": "/docs/",
    "/en/docs/index": "/en/docs/",
  },

  integrations: [
    starlight({
      plugins: [
        starlightLinksValidator({
          // Same-page and relative links are fine; only flag links whose
          // target page doesn't exist.
          errorOnRelativeLinks: false,
          // Not all pages are translated; English routes intentionally fall
          // back to the Dutch content, so links to them are valid.
          errorOnFallbackPages: false,
        }),
      ],
      title: {
        nl: "RoQua Documentatie",
        en: "RoQua Documentation",
      },
      // The top bar is always dark, so the white wordmark works in both themes.
      logo: {
        src: "./src/assets/wordmark-white.svg",
        alt: "RoQua",
        replacesTitle: true,
      },
      favicon: "/img/favicon.ico",

      components: {
        Header: "./src/components/Header.astro",
        Hero: "./src/components/Hero.astro",
        PageTitle: "./src/components/PageTitle.astro",
      },

      // Code blocks are dark in both themes, per the design.
      expressiveCode: {
        themes: ["github-dark"],
        styleOverrides: {
          borderRadius: "0.5rem",
          borderColor: "var(--sl-color-hairline)",
          codeBackground: "oklch(0.21 0.04 266)",
          frames: {
            editorTabBarBackground: "oklch(0.26 0.035 266)",
            editorActiveTabBackground: "oklch(0.21 0.04 266)",
            editorActiveTabIndicatorTopColor: "transparent",
            editorActiveTabIndicatorBottomColor: "oklch(0.68 0.16 254)",
            terminalBackground: "oklch(0.21 0.04 266)",
            terminalTitlebarBackground: "oklch(0.26 0.035 266)",
            terminalTitlebarBorderBottomColor: "rgb(255 255 255 / 0.08)",
          },
        },
      },

      defaultLocale: "root",
      locales: {
        root: { label: "Nederlands", lang: "nl" },
        en: { label: "English", lang: "en" },
      },

      editLink: {
        baseUrl: "https://github.com/roqua/documentation/edit/master/",
      },

      customCss: [
        "@fontsource-variable/roboto/standard.css",
        "@fontsource-variable/roboto/standard-italic.css",
        "./src/styles/custom.css",
      ],

      // Recovers the Docusaurus category labels for autogenerated groups.
      routeMiddleware: "./src/starlightRouteData.ts",

      sidebar: [
        {
          label: "Gebruikershandleiding",
          translations: { en: "User Manual" },
          items: [{ autogenerate: { directory: "docs", collapsed: true } }],
        },
        {
          label: "Technische handleiding",
          translations: { en: "Technical documentation" },
          items: [{ autogenerate: { directory: "technical", collapsed: true } }],
        },
        { slug: "status" },
      ],
    }),
  ],

  vite: {
    resolve: {
      alias: {
        "@components": new URL("./src/components", import.meta.url).pathname,
        "@snapshots": new URL("./src/data/snapshots", import.meta.url).pathname,
      },
    },
  },
});
