// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

export default defineConfig({
  site: "https://docs.roqua.net",

  // The manual root used to be /docs/index/, an artifact of the `01-index.md`
  // numeric prefix. It was the navbar's "User Manual" target, so keep it working.
  redirects: {
    "/docs/index": "/docs/",
    "/en/docs/index": "/en/docs/",
  },

  integrations: [
    starlight({
      title: {
        nl: "RoQua Documentatie",
        en: "RoQua Documentation",
      },
      logo: {
        src: "./src/assets/roqua-q.png",
        alt: "RoQua Logo",
      },
      favicon: "/img/favicon.ico",

      defaultLocale: "root",
      locales: {
        root: { label: "Nederlands", lang: "nl" },
        en: { label: "English", lang: "en" },
      },

      editLink: {
        baseUrl: "https://github.com/roqua/documentation/edit/master/",
      },

      customCss: ["./src/styles/custom.css"],

      // Recovers the Docusaurus category labels for autogenerated groups.
      routeMiddleware: "./src/starlightRouteData.ts",

      sidebar: [
        {
          label: "Gebruikershandleiding",
          translations: { en: "User Manual" },
          items: [{ autogenerate: { directory: "docs", collapsed: true } }],
        },
        {
          label: "Technische handleiding",
          translations: { en: "Technical documentation" },
          items: [{ autogenerate: { directory: "technical", collapsed: true } }],
        },
        { slug: "status" },
      ],
    }),
  ],

  vite: {
    resolve: {
      alias: {
        "@components": new URL("./src/components", import.meta.url).pathname,
        "@snapshots": new URL("./src/data/snapshots", import.meta.url).pathname,
      },
    },
  },
});
