import { defineRouteMiddleware, type StarlightRouteData } from "@astrojs/starlight/route-data";

type SidebarEntry = StarlightRouteData["sidebar"][number];

/**
 * Label autogenerated sidebar groups after their index page.
 *
 * Starlight labels an autogenerated group with the raw directory name, which would
 * turn "EPD-module" into "epd". Docusaurus used the title of the directory's index
 * page instead, and every directory here has one, so we can recover those labels
 * without maintaining a lookup table — and it keeps working for new directories.
 */

/** The href of the first page reachable in an entry, used to compare nesting depth. */
function firstHref(entry: SidebarEntry): string {
  if (entry.type === "link") return entry.href;
  for (const child of entry.entries) {
    const href = firstHref(child);
    if (href) return href;
  }
  return "";
}

/**
 * The index page of a group is the one whose href is a prefix of every sibling's,
 * since sibling pages live inside the index page's directory.
 */
function findIndexEntry(entries: SidebarEntry[]) {
  return entries.find(
    (entry) =>
      entry.type === "link" &&
      entries.every((other) => other === entry || firstHref(other).startsWith(entry.href)),
  );
}

function relabelGroups(entries: SidebarEntry[]) {
  for (const entry of entries) {
    if (entry.type !== "group") continue;
    relabelGroups(entry.entries);
    // Groups declared in astro.config.mjs already have deliberate, translated
    // labels; only autogenerated ones fall back to a bare directory name.
    if (!("autogenerate" in entry)) continue;
    const indexEntry = findIndexEntry(entry.entries);
    if (indexEntry) entry.label = indexEntry.label;
  }
}

export const onRequest = defineRouteMiddleware((context) => {
  relabelGroups(context.locals.starlightRoute.sidebar);
});
